Specify a container name when using Podman
A container name needs to be specified, otherwise you get the following error message.

```
Error: error running container create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument
```